version: "3.9"
services:
  notes:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PASSWORD=${PASSWORD}
      - UPSTASH_URL=${UPSTASH_URL}
      - UPSTASH_TOKEN=${UPSTASH_TOKEN}
      - WEBDAV_URL=${WEBDAV_URL}
      - WEBDAV_USER=${WEBDAV_USER}
      - WEBDAV_PASS=${WEBDAV_PASS}
    restart: unless-stopped

