name: 推送Docker镜像

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: latest

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出源代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录 GitHub 容器注册表
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Docker Hub 环境变量
        run: |
          echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" >> $GITHUB_ENV
          echo "DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}" >> $GITHUB_ENV

      - name: 登录 Docker Hub
        if: ${{ env.DOCKER_USER != '' && env.DOCKER_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: 提取镜像元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKER_USER && format('{0}/{1}', env.DOCKER_USER, env.IMAGE_NAME) || '' }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: 构建并推送多架构镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
